/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TwinRouteImport } from './routes/twin'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as JourneysRouteImport } from './routes/journeys'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as HealthRouteImport } from './routes/health'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'

const TwinRoute = TwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysRoute = JourneysRouteImport.update({
  id: '/journeys',
  path: '/journeys',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/assistant': typeof AssistantRoute
  '/documents': typeof DocumentsRoute
  '/explore': typeof ExploreRoute
  '/goals': typeof GoalsRoute
  '/health': typeof HealthRoute
  '/insights': typeof InsightsRoute
  '/journeys': typeof JourneysRoute
  '/notifications': typeof NotificationsRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/transactions': typeof TransactionsRoute
  '/twin': typeof TwinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/assistant': typeof AssistantRoute
  '/documents': typeof DocumentsRoute
  '/explore': typeof ExploreRoute
  '/goals': typeof GoalsRoute
  '/health': typeof HealthRoute
  '/insights': typeof InsightsRoute
  '/journeys': typeof JourneysRoute
  '/notifications': typeof NotificationsRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/transactions': typeof TransactionsRoute
  '/twin': typeof TwinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/assistant': typeof AssistantRoute
  '/documents': typeof DocumentsRoute
  '/explore': typeof ExploreRoute
  '/goals': typeof GoalsRoute
  '/health': typeof HealthRoute
  '/insights': typeof InsightsRoute
  '/journeys': typeof JourneysRoute
  '/notifications': typeof NotificationsRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/transactions': typeof TransactionsRoute
  '/twin': typeof TwinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/assistant'
    | '/documents'
    | '/explore'
    | '/goals'
    | '/health'
    | '/insights'
    | '/journeys'
    | '/notifications'
    | '/portfolio'
    | '/profile'
    | '/settings'
    | '/sitemap.xml'
    | '/support'
    | '/transactions'
    | '/twin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/assistant'
    | '/documents'
    | '/explore'
    | '/goals'
    | '/health'
    | '/insights'
    | '/journeys'
    | '/notifications'
    | '/portfolio'
    | '/profile'
    | '/settings'
    | '/sitemap.xml'
    | '/support'
    | '/transactions'
    | '/twin'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/assistant'
    | '/documents'
    | '/explore'
    | '/goals'
    | '/health'
    | '/insights'
    | '/journeys'
    | '/notifications'
    | '/portfolio'
    | '/profile'
    | '/settings'
    | '/sitemap.xml'
    | '/support'
    | '/transactions'
    | '/twin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AssistantRoute: typeof AssistantRoute
  DocumentsRoute: typeof DocumentsRoute
  ExploreRoute: typeof ExploreRoute
  GoalsRoute: typeof GoalsRoute
  HealthRoute: typeof HealthRoute
  InsightsRoute: typeof InsightsRoute
  JourneysRoute: typeof JourneysRoute
  NotificationsRoute: typeof NotificationsRoute
  PortfolioRoute: typeof PortfolioRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TransactionsRoute: typeof TransactionsRoute
  TwinRoute: typeof TwinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/twin': {
      id: '/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof TwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys': {
      id: '/journeys'
      path: '/journeys'
      fullPath: '/journeys'
      preLoaderRoute: typeof JourneysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AssistantRoute: AssistantRoute,
  DocumentsRoute: DocumentsRoute,
  ExploreRoute: ExploreRoute,
  GoalsRoute: GoalsRoute,
  HealthRoute: HealthRoute,
  InsightsRoute: InsightsRoute,
  JourneysRoute: JourneysRoute,
  NotificationsRoute: NotificationsRoute,
  PortfolioRoute: PortfolioRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TransactionsRoute: TransactionsRoute,
  TwinRoute: TwinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
